[package]
name = "fumo_database"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "fumo_database"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.38"
eyre = "0.6.12"
sqlx = { version = "0.8.2", features = [ "runtime-tokio-native-tls" , "postgres", "chrono" ] }
