[package]
name = "fumo_potato"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
chrono = "0.4.22"
dotenv = "0.15.0"
eyre = "0.6.8"
log = "0.4.17"
num-format = "0.4.0"
once_cell = "1.15.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = "0.1.11"
twilight = "0.14.0"
twilight-gateway = "0.14.0"
twilight-http = "0.14.0"
twilight-model = "0.14.0"
twilight-standby = "0.14.0"
twilight-util = { version = "0.14.0", features = ["builder"] }

[profile.release]
opt-level = 3
