[package]
name = "fumo_potato"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
bitflags = "1.3.2"
chrono = "0.4.22"
dotenv = "0.15.0"
num-format = "0.4.0"
once_cell = "1.15.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = "0.1.11"
twilight = "0.13.0"
twilight-gateway = "0.13.3"
twilight-http = "0.13.3"
twilight-model = "0.13.7"
twilight-standby = "0.13.2"
twilight-util = { version = "0.13.3", features = ["builder"] }

[profile.release]
opt-level = 3
