[package]
name = "fumo_macro"
version = { workspace = true }
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.89", features = ["full"] }
fumo_twilight = { workspace = true }
twilight-model = "0.15.4"
